# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  test:
    name: Test Project with e2e
    strategy:
      matrix:
        node-version: [ 16.9 ]
        os: [ ubuntu-latest, windows-latest,macos-latest ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn
    - run: yarn e2e
  build:
    name: Build project using electron-builder
    strategy:
      matrix:
        node-version: [ 16.9 ]
        os: [ ubuntu-latest, windows-latest,macos-latest ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ${{ matrix.os }}

    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn
    - name: build other-platforms
      if: ${{ ${{ matrix.os }} ! 'ubuntu-latest' }}
      run: yarn release
    - name: build debian package
      if: ${{ matrix.os }} == 'ubuntu-latest'
      run: |
        sudo snap install snapcraft --classic
        yarn build-deb